version: '3.9'
services:
  db:
    container_name: gces_postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: 
      - 5432:5432
    volumes:
      - gces_db:/var/lib/postgresql/data
    networks:
      - gces_app_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    container_name: gces_app
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/gces_app_vol
    networks:
      - gces_app_net
    depends_on:
      db:
        condition: service_healthy
    
  gces_nginx:
    container_name: gces_nginx
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - gces_app_net
    depends_on:
      - app

networks:
  gces_app_net:
    external: true

volumes:
  gces_db: