name: gces_CI

on:

  pull_request:
    branches: [ main, development ]

  workflow_dispatch:
  workflow_call:
  
jobs:
#Lint ================================================================================================

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name:  Create app network
        working-directory: ./aplicacao
        run: docker network create gces_app_net 

      - name: Build app and db
        working-directory: ./aplicacao
        run: docker-compose up -d app

      - name: Install Lint
        working-directory: ./aplicacao
        run: docker exec gces_app gem install rubocop

      - name: Run Lint
        working-directory: ./aplicacao
        run: docker exec gces_app rubocop -A --fail-level F
        
#Build ===============================================================================================

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create app network
        working-directory: ./aplicacao
        run: docker network create gces_app_net 
        
      - name: Build the stack
        working-directory: ./aplicacao
        run: docker-compose up -d

#Test ================================================================================================

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create app network
        working-directory: ./aplicacao
        run: docker network create gces_app_net 
        
      - name: Build app and db
        working-directory: ./aplicacao
        run: docker-compose up -d app
        
      - name: Run tests
        working-directory: ./aplicacao
        run: docker exec gces_app rails db:reset && docker exec gces_app rspec 