name: gces_CI
# Controls when the workflow will run
on:
  pull_request:
    branches: [ main, development ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
#Build ===============================================================================================
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
       
      - uses: actions/checkout@v3
      - name: Create app network
        working-directory: ./aplicacao
        run: docker network create gces_app_net 
        
      - name: Build the stack
        working-directory: ./aplicacao
        run: docker-compose up -d
  #Test ============================================================================================== 
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create app network
        working-directory: ./aplicacao
        run: docker network create gces_app_net 
        
      - name: Build app and db
        working-directory: ./aplicacao
        run: docker-compose up -d app
        
      - name: Run tests
        working-directory: ./aplicacao
        run: docker exec gces_app rails db:reset && docker exec gces_app rspec 